<a href="https://colab.research.google.com/github/TianaT6/MSSP607/blob/main/Modules/Week_6/MSSP607_Week6_Participation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Week 6: Lambda Function for a DataFrame

## 1. Load the data

In [2]:
import pandas as pd
from pathlib import Path

file_path = Path("data/Student Performance Data.csv")
if not file_path.exists():
    file_path = Path("Student Performance Data.csv")
if not file_path.exists():
    from google.colab import files
    uploaded = files.upload()
    file_path = next(iter(uploaded))

students = pd.read_csv(file_path)
print("Original shape:", students.shape)
students.head()

Saving Student Performance Data.csv to Student Performance Data.csv
Original shape: (1000, 10)

,gender,race/ethnicity,parental level of education,lunch,math score,reading score,writing score,total score,test preparation course,admission prospect
0,female,group B,bachelor's degree,standard,72,72,74,218,none,medium
1,female,group C,some college,standard,69,90,88,247,completed,high
2,female,group B,master's degree,standard,90,95,93,278,none,high
3,male,group A,associate's degree,free/reduced,47,57,44,148,none,low
4,male,group C,some college,standard,76,78,75,229,none,high

## 2. Define and call the lambda

The parameter `df` receives the whole DataFrame. `assign()` returns a new DataFrame with an `average_score` column. The original DataFrame stays unchanged.

In [3]:
add_average = lambda df: df.assign(
    average_score=((df["math score"] + df["reading score"] + df["writing score"]) / 3).round(2)
)

students_with_average = add_average(students)
students_with_average.head()

,gender,race/ethnicity,parental level of education,lunch,math score,reading score,writing score,total score,test preparation course,admission prospect,average_score
0,female,group B,bachelor's degree,standard,72,72,74,218,none,medium,72.67
1,female,group C,some college,standard,69,90,88,247,completed,high,82.33
2,female,group B,master's degree,standard,90,95,93,278,none,high,92.67
3,male,group A,associate's degree,free/reduced,47,57,44,148,none,low,49.33
4,male,group C,some college,standard,76,78,75,229,none,high,76.33

## 3. Check the result

The result should be a DataFrame with 1,000 rows and 11 columns. For the first student, the average is (72 + 72 + 74) / 3 = 72.67 after rounding.

In [4]:
print("Result type:", type(students_with_average))
print("Original shape:", students.shape)
print("New shape:", students_with_average.shape)
print("Original has average_score:", "average_score" in students.columns)
print("First student average:", students_with_average.loc[0, "average_score"])

Result type: <class 'pandas.core.frame.DataFrame'>
Original shape: (1000, 10)
New shape: (1000, 11)
Original has average_score: False
First student average: 72.67

## 4. Save the new DataFrame

The CSV is saved in the current working folder. In Colab, it appears in the Files panel.

In [5]:
students_with_average.to_csv("Student_Performance_With_Average.csv", index=False)
print("Saved: Student_Performance_With_Average.csv")

Saved: Student_Performance_With_Average.csv